### ISSUE TITLE
Illegal instructions in packages

### ISSUE THREAD

**Issue by tomkooij** [conda-forge/pytables-feedstock#23]
`Illegal instruction` errors are reported with conda-forge built pytables packages: PyTables/PyTables#458

This is most probably the seem issue as MacPython/pytables-wheels#8

The pytables built-in BLOSC package is probably the culprit: It will force AVX2 instruction generation.

**Comment by tomkooij** [comment]
I can confirm the `SIGILL`  on the most recent package: `pytables                  3.4.2               np113py36_3    conda-forge`

In the CircleCI log there is indeed `-DSHUFFLE_AVX2_ENABLED -mavx2`

**Comment by isuruf** [comment]
FYI, CircleCI has added `haswell` (haswell supports AVX2) machines recently. It was `ivybridge` before which doesn't support AVX2. That's why the sudden failure. https://discuss.circleci.com/t/use-the-arch-cache-template-key-if-you-rely-on-cached-compiled-binary-dependencies/16129/2
