### ISSUE TITLE
python 3.5.x segfault with zlib>=1.2.8

### ISSUE THREAD

**Issue by tomkooij** [conda-forge/pytables-feedstock#27]
```
Python 3.5.4 | packaged by conda-forge | (default, Dec 18 2017, 06:30:33)
[GCC 4.8.2 20140120 (Red Hat 4.8.2-15)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tables
>>> import matplotlib.pyplot as plt
Segmentation fault
```

Reported in:
https://github.com/ContinuumIO/anaconda-issues/issues/7315
PyTables/PyTables#644

I can reproduce this on `python=3.5` but not on python 3.6.

Solution is probably pin zlib to 1.2.8, but this might break hdf5. Will test with PR.

**Comment by laborleben** [comment]
Thanks for posting the issue.

Pinning zlib to 1.2.8 is one solution. Another is to ```import zilb``` at the very beginning of the modules. The second variant is also working with zlib>=1.2.8. So I conclude that there is no general incompatibility with zlib>1.2.8 (I'm not aware of any zlib==1.2.8 installation on my partition during my tests).

**Comment by tomkooij** [comment]
We cannot pin `zlib` to 1.2.8 for python 3.5 because `hdf5` 1.10 is pinned to `zlib==1.2.11`.

I guess we need to leave this open, until we find the actual cause for the segfault.
