### ISSUE TITLE
PyTables conda build does not include blosc and will segfault with newer hdf5/zlib

### ISSUE THREAD

**Issue by EricR86** [conda-forge/pytables-feedstock#41]
Issue:
Nearly identical to Issue #39. Blosc is not being built in with the recipe so the python extension utilsextension.so still has internal symbols for zlib which may cause a segfault using the same test case as posted in Issue #39. This can be verified by downloading the [current package](https://anaconda.org/conda-forge/pytables/3.4.4/download/linux-64/pytables-3.4.4-py36h2392372_2.tar.bz2) off the anaconda cloud and running `nm` on the utilsextension on the shared object:
 ```bash
    $ nm site-packages/tables/utilsextension.cpython-36m-x86_64-linux-gnu.so | rg deflate
    000000000006a010 T deflate
    0000000000069ec0 T deflateBound
    000000000006baa0 T deflateCopy
    0000000000103b60 R deflate_copyright
    000000000006b680 T deflateEnd
    0000000000068940 t deflate_fast
    000000000006ba70 T deflateInit_
    000000000006b770 T deflateInit2_
    000000000006b550 T deflateParams
    0000000000069d90 T deflatePending
    0000000000069dd0 T deflatePrime
    0000000000069c80 T deflateReset
    0000000000069bb0 T deflateResetKeep
    0000000000069970 T deflateSetDictionary
    0000000000069d60 T deflateSetHeader
    0000000000068ec0 t deflate_slow
    00000000000695e0 t deflate_stored
    0000000000069e80 T deflateTune
                    U H5Pset_deflate
```

The issue should be fixed by including blosc in the build requirements for the recipe.

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list
N/A
```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>
N/A
```
$ conda info

```
</details>

**Comment by scopatz** [comment]
Thanks for reporting @EricR86! Feel free to PR yourself in as a maintainer and add a fix!
