### ISSUE TITLE
Python 3.5 builds are no longer being updated

### ISSUE THREAD

**Issue by EricR86** [conda-forge/pytables-feedstock#45]
Issue:

PyTables conda builds are no longer being built for Python 3.5. They still have older build bugs (relating to not using blosc and segfaulting). I found the change in commit [dbd14143]( https://github.com/conda-forge/pytables-feedstock/commit/dbd14143ce03713e8bdffecf349190aaddcf672e#diff-1d37e48f9ceff6d8030570cd36286a61). Travis no longer provides conda builds for Python 3.5 as also evidence on the anaconda package list.

I'm not sure why this particular build was dropped or the rational. It would be great to figure out why this happened. If there's no future support planned for Python 3.5 on conda it would be great to know as well.

Thanks!

**Comment by scopatz** [comment]
conda-forge no longer supports Python 3.5, at the current time.

**Comment by EricR86** [comment]
@scopatz do you have any reference for that? I cannot find it through the usual googling.
This would be great to know since other channels are still building against Python 3.5 and I would like raise an issue with them.

**Comment by scopatz** [comment]
I know we made announcements about it in a couple of places, but here is the tweet: https://twitter.com/condaforge/status/1045699331171528707

**Comment by EricR86** [comment]
Perfect thank you so much.

**Comment by EricR86** [comment]
Since conda-forge no longer support Python 3.5 this makes sense.
