### ISSUE TITLE
lzo GPL dynamic linking

### ISSUE THREAD

**Issue by dgasmith** [conda-forge/pytables-feedstock#70]
- [x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:

While pytables appears to be licensed under [BSD-3c](https://github.com/conda-forge/pytables-feedstock/blob/master/recipe/meta.yaml#L72), it dynamically links lzo (on linux) which is [GPL2](https://www.gnu.org/licenses/gpl-faq.html#InternalDistribution). Natively this appears to violate the GPL, is there any information if pytables has some sort of special dispensation?

```bash
ldd _comp_lzo.cpython-39-x86_64-linux-gnu.so
	liblzo2.so.2 => /opt/conda/envs/testtables/lib/python3.9/site-packages/tables/./../../../liblzo2.so.2 (0x00007f7799c41000)
```

**Comment by jakirkham** [comment]
Maybe the thing to do would be to build two variants on with and one without GPL bits?

Wrote up some ideas on how we can make this into a scheme usable across conda-forge and easier for users to work with ( https://github.com/conda-forge/conda-forge.github.io/issues/1608 ). Feedback welcome 🙂
