### ISSUE TITLE
LZO missing or not detected on 64-bit Windows when via conda-forge

### ISSUE THREAD

**Issue by erik-mansson** [conda-forge/pytables-feedstock#93]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

Installing pytables from Anaconda defaults (main) channel includes the lzo package and pytables finds LZO 2.10, but when installing from conda-forge (with mamba in Miniforge) the lzo package is not included. Adding the lzo 2.10 package separately still does not make pytables find it (or its DLL).

I found https://github.com/conda-forge/pytables-feedstock/issues/70 with a proposal to stop including LZO but as the issue is still open, I doubt that it would have lead to changes causing my problem. The BSD 3-clause license applies to pytables both via the anaconda and conda-forge channels. The [lzo package](https://github.com/conda-forge/lzo-feedstock) does exists in conda-forge so it seems to me that the problem is more about it not being listed as a dependency or not being found.

My main motivation for preferring conda-forge is that Anaconda's terms and conditions does not allow  non-educational organizations to use the main channel for free (even if they are non-commercial research organizations outside USA), so I would hope there could be a binary package with lzo also in the community channel. I guess https://github.com/AnacondaRecipes/pytables-feedstock is what Anaconda defaults (main) use and since it is a fork of the conda-forge repository I was hoping a comparison would reveal why or how the difference arises. But without being familiar with packaging tools, I was not able to identify any interesting LZO-differences after a quick look.

If it would be concluded that there are licensing problems with the way LZO is included as a compiled DLL in the defaults/main channel, I'd like it to be documented somewhere that this difference exists for conda-forge. If this is the case, it would be a regression of ease of use and I would then open a separate issue for pytables documentation to offer more precise [installation help](https://www.pytables.org/usersguide/installation.html) (they discuss how to compile with LZO on Windows or to use a package and place (outdated version) lzo1.dll in a folder on the PATH -- and despite some hours of trying I so far had no success getting pytables from conda-forge to recognize lzo from conda-forge regardless of me placing the DLL in various paths).

### Steps to reproduce
I used a fresh installation of [Miniforge3-Windows-x86_64](https://github.com/conda-forge/miniforge) on Windows 10. I was hoping that using Miniforge and mamba would automatically force the conda-forge channel but [perhaps due to an old .condarc](https://github.com/mamba-org/mamba/issues/656) from an otherwise removed Anaconda installation, my first attempt inadvertently used the Anaconda defaults (main) channel. LZO in pytables works then, but when repeating to use conda-forge as I wanted LZO disappears. So I write steps to reproduce in this order. (Feel free to try whether simply using `conda install -c defaults ...` vs.  `conda install -c conda-forge ...` reproduces the issue, I didn't check in that way yet.)

First, what worked with Anaconda's main repository:
1. Ensure that `mamba info` or `conda info` shows channel URLs including "https://repo.anaconda.com/pkgs/main/", use `conda config --add channels defaults` if necessary.
2. `mamba create -n works "python=3.10"`
3. `mamba activate works`
4. `mamba install "pytables>=3.8" ipython`
5. `ipython -c "import tables; tables.print_versions(); tables.filters.Filters(1, 'lzo')"` This will list the LZO version and will create a filter with lzo as complib.
6. Document by `mamba list --explicit >works.txt`
7. Clean up by `mamba deactivate` and `mamba uninstall -n works --all`

Then what did not work, with conda-forge:
1. `conda config --add channels conda-forge` and  `conda config --remove channels defaults` and ensure that `mamba info`  only lists URLs beginning with https://conda.anaconda.org/conda-forge/.
2. `mamba create -n issue "python=3.10"`
3. `mamba activate issue`
4. `mamba install "pytables>=3.8" ipython`
5. `ipython -c "import tables; tables.print_versions(); tables.filters.Filters(1, 'lzo')"` This did NOT show any LZO version and when trying to create the filter a warning a printed and you get zlib instead.
6. Document by `mamba list --explicit >missing.txt` You will notice that the lzo packge was not even installed, so the dependencies must have been specified differently in conda-forge than in Anaconda defaults.
7. `mamba install lzo` to make sure we have the lzo package and a lzo2.dll. I saved the result by `mamba list --explicit >not_recognized.txt`.
8. Repeating step 5 still fails to find LZO. (I also tried to uninstall pytables and reinstall after lzo was installed, but still not working.)
9. Optionally clean up by `mamba deactivate` and `mamba uninstall -n issue --all`

### The resulting explicit lists of packages
[works.txt](https://github.com/conda-forge/pytables-feedstock/files/12883097/works.txt)
[missing.txt](https://github.com/conda-forge/pytables-feedstock/files/12883095/missing.txt) (Also pasted in textbox.)
[not_recognized.txt](https://github.com/conda-forge/pytables-feedstock/files/12883096/not_recognized.txt)

### Installed packages

```shell
# This file may be used to create an environment using:
# $ conda create --name <env> --file <this file>
# platform: win-64
@EXPLICIT
https://conda.anaconda.org/conda-forge/win-64/ca-certificates-2023.7.22-h56e8100_0.conda
https://conda.anaconda.org/conda-forge/noarch/llvm-meta-5.0.0-0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/nomkl-1.0-h5ca1d4c_0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/python_abi-3.10-4_cp310.conda
https://conda.anaconda.org/conda-forge/noarch/tzdata-2023c-h71feb2d_0.conda
https://conda.anaconda.org/conda-forge/win-64/ucrt-10.0.22621.0-h57928b3_0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/vc14_runtime-14.36.32532-hdcecf7f_17.conda
https://conda.anaconda.org/conda-forge/win-64/vc-14.3-h64f974e_17.conda
https://conda.anaconda.org/conda-forge/win-64/vs2015_runtime-14.36.32532-h05e6639_17.conda
https://conda.anaconda.org/conda-forge/win-64/bzip2-1.0.8-h8ffe710_4.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/libaec-1.1.2-h63175ca_1.conda
https://conda.anaconda.org/conda-forge/win-64/libffi-3.4.2-h8ffe710_5.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/libsqlite-3.43.2-hcfcfb64_0.conda
https://conda.anaconda.org/conda-forge/win-64/libzlib-1.2.13-hcfcfb64_5.conda
https://conda.anaconda.org/conda-forge/win-64/lz4-c-1.9.4-hcfcfb64_0.conda
https://conda.anaconda.org/conda-forge/win-64/lzo-2.10-he774522_1000.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/openmp-5.0.0-vc14_1.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/openssl-3.1.3-hcfcfb64_0.conda
https://conda.anaconda.org/conda-forge/win-64/snappy-1.1.10-hfb803bf_0.conda
https://conda.anaconda.org/conda-forge/win-64/tk-8.6.13-hcfcfb64_0.conda
https://conda.anaconda.org/conda-forge/win-64/xz-5.2.6-h8d14728_0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/zlib-ng-2.0.7-hcfcfb64_0.conda
https://conda.anaconda.org/conda-forge/win-64/krb5-1.21.2-heb0366b_0.conda
https://conda.anaconda.org/conda-forge/win-64/libflang-5.0.0-h6538335_20180525.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/libssh2-1.11.0-h7dfc565_0.conda
https://conda.anaconda.org/conda-forge/win-64/python-3.10.12-h4de0772_0_cpython.conda
https://conda.anaconda.org/conda-forge/win-64/zstd-1.5.5-h12be248_0.conda
https://conda.anaconda.org/conda-forge/noarch/backcall-0.2.0-pyh9f0ad1d_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/backports-1.0-pyhd8ed1ab_3.conda
https://conda.anaconda.org/conda-forge/win-64/blosc-1.21.5-hdccc3a2_0.conda
https://conda.anaconda.org/conda-forge/win-64/c-blosc2-2.10.5-h183a6f4_0.conda
https://conda.anaconda.org/conda-forge/noarch/colorama-0.4.6-pyhd8ed1ab_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/decorator-5.1.1-pyhd8ed1ab_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/exceptiongroup-1.1.3-pyhd8ed1ab_0.conda
https://conda.anaconda.org/conda-forge/noarch/executing-1.2.0-pyhd8ed1ab_0.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/libcurl-8.4.0-hd5e4a3a_0.conda
https://conda.anaconda.org/conda-forge/win-64/libopenblas-0.3.24-pthreads_hc140b1d_0.conda
https://conda.anaconda.org/conda-forge/noarch/packaging-23.2-pyhd8ed1ab_0.conda
https://conda.anaconda.org/conda-forge/noarch/parso-0.8.3-pyhd8ed1ab_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/pickleshare-0.7.5-py_1003.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/pure_eval-0.2.2-pyhd8ed1ab_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/py-cpuinfo-9.0.0-pyhd8ed1ab_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/pygments-2.16.1-pyhd8ed1ab_0.conda
https://conda.anaconda.org/conda-forge/noarch/setuptools-68.2.2-pyhd8ed1ab_0.conda
https://conda.anaconda.org/conda-forge/noarch/six-1.16.0-pyh6c4a22f_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/traitlets-5.11.2-pyhd8ed1ab_0.conda
https://conda.anaconda.org/conda-forge/noarch/typing_extensions-4.8.0-pyha770c72_0.conda
https://conda.anaconda.org/conda-forge/noarch/wheel-0.41.2-pyhd8ed1ab_0.conda
https://conda.anaconda.org/conda-forge/noarch/asttokens-2.4.0-pyhd8ed1ab_0.conda
https://conda.anaconda.org/conda-forge/noarch/backports.functools_lru_cache-1.6.5-pyhd8ed1ab_0.conda
https://conda.anaconda.org/conda-forge/win-64/hdf5-1.14.2-nompi_h73e8ff5_100.conda
https://conda.anaconda.org/conda-forge/noarch/jedi-0.19.1-pyhd8ed1ab_0.conda
https://conda.anaconda.org/conda-forge/win-64/libblas-3.9.0-18_win64_openblas.conda
https://conda.anaconda.org/conda-forge/noarch/matplotlib-inline-0.1.6-pyhd8ed1ab_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/pip-23.2.1-pyhd8ed1ab_0.conda
https://conda.anaconda.org/conda-forge/win-64/libcblas-3.9.0-18_win64_openblas.conda
https://conda.anaconda.org/conda-forge/win-64/liblapack-3.9.0-18_win64_openblas.conda
https://conda.anaconda.org/conda-forge/noarch/stack_data-0.6.2-pyhd8ed1ab_0.conda
https://conda.anaconda.org/conda-forge/noarch/wcwidth-0.2.8-pyhd8ed1ab_0.conda
https://conda.anaconda.org/conda-forge/win-64/numpy-1.26.0-py310hf667824_0.conda
https://conda.anaconda.org/conda-forge/noarch/prompt-toolkit-3.0.39-pyha770c72_0.conda
https://conda.anaconda.org/conda-forge/win-64/numexpr-2.8.7-py310h27d5182_103.conda
https://conda.anaconda.org/conda-forge/noarch/prompt_toolkit-3.0.39-hd8ed1ab_0.conda
https://conda.anaconda.org/conda-forge/noarch/ipython-8.16.1-pyh5737063_0.conda
https://conda.anaconda.org/conda-forge/win-64/pytables-3.9.1-py310hde27e41_0.conda
```

### Environment info

```shell
active environment : base
    active env location : C:\Users\REDACTED\miniforge3
            shell level : 1
       user config file : C:\Users\REDACTED\.condarc
 populated config files : C:\Users\REDACTED\miniforge3\.condarc
                          C:\Users\REDACTED\.condarc
          conda version : 23.3.1
    conda-build version : not installed
         python version : 3.10.12.final.0
       virtual packages : __archspec=1=x86_64
                          __win=0=0
       base environment : C:\Users\REDACTED\miniforge3  (writable)
      conda av data dir : C:\Users\REDACTED\miniforge3\etc\conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : C:\Users\REDACTED\miniforge3\pkgs
                          C:\Users\REDACTED\.conda\pkgs
                          C:\Users\REDACTED\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\REDACTED\miniforge3\envs
                          C:\Users\REDACTED\.conda\envs
                          C:\Users\REDACTED\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/23.3.1 requests/2.31.0 CPython/3.10.12 Windows/10 Windows/10.0.19045
          administrator : False
             netrc file : None
           offline mode : Fals
```

**Comment by avalentino** [comment]
Dear @erik-mansson sorry for the late reply.
Looking at the [recipe](https://github.com/conda-forge/pytables-feedstock/blob/main/recipe/meta.yaml) to build the PyTables conda package in conda-forge, it seems that `lzo` is only specified as a dependency on linux, not on windows.
I ignore the reason, honestly, but for sure if the binary package of PyTables has been built without support for LZO, there is no way to add it by simply installing the lzo package.

**Comment by avalentino** [comment]
According to #70, PyTables v3.10.1 is now providing wheel packages without lzo.
Moreover we have removed lzo also from the linux version of the conda-package.
Closing
Please feel free to re-open if you do not agree
